const prompt = require("prompt-sync")()
let nota1 = Number(prompt("Qual a primeira nota?"))
let nota2 = Number(prompt("Qual a segunda nota?"))
let media = ( (nota1 + nota2) / 2)
console.log (`Sua media é ${media}`)